name: VirtualStorages
version: 1.4.0.0
author: DaveDuart
description: |
  Provides virtual backpacks so that your players can 
  store and access their items from any location
main: net.duart.virtualstorage.VirtualStorages
api-version: '1.20'

commands:
  backpack:
    description: Opens the virtual backpack inventory.
    usage: /backpack
    aliases: [bp]
  backpackview:
    description: Allows the player to open another user's inventory.
    usage: /backpackview <PlayerName>
    aliases: [bpview]
    permission: virtualstorages.admin
  vsreload:
    description: Reloads the language file.
    usage: /vsreload
    permission: virtualstorages.admin